# =============================================================================
# SAL Example Adapter — reference configuration
# =============================================================================

sal:
  adapter:
    name: example-adapter
    type: ExampleAdapter
  service:
    environment-key: ""
    sal-version: 1
  command:
    threads: 10
    result-threads: 10

spring:
  application:
    name: ${sal.adapter.name}
  main:
    web-application-type: none
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: dev
    username: guest
    password: guest
  lifecycle:
    timeout-per-shutdown-phase: 30s
